# Site settings
title: Neha Sharma
academic_email: nehash@wharton.upenn.edu

description: > # this means to ignore newlines until "baseurl:"
  I am an Assistant Professor of Operations, Information, and Decisions at The Wharton School, University of Pennsylvania. My research focuses on the design of online marketplaces using data, stochastic models, and game theory. 

baseurl: # "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://neha-sharma-research.github.io"

# twitter_username: jekyllrb
github_username: neha-sharma-research
linkedin_username: neha-sharma-wharton
# facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
